[program:phoenixd]
command=phoenixd --datadir=%(ENV_PHOENIXD_DATADIR)s --agree-to-terms-of-service --http-bind-ip=127.0.0.1
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
