[program:bitcoind]
command=bitcoind -datadir=%(ENV_BITCOIND_DATADIR)s -conf=%(ENV_BITCOIND_DATADIR)s/bitcoin.conf
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
