[program:phoenixd]
command=phoenixd --seed-path=%(ENV_PHOENIXD_DATADIR)s/.phoenix/seed.dat --agree-to-terms-of-service --http-bind-ip=127.0.0.1 --chain=mainnet
environment=HOME="%(ENV_PHOENIXD_DATADIR)s"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
