[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root

[include]
files = /etc/supervisor/conf.d/*.conf

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[unix_http_server]
file=/var/run/supervisor.sock
